point to basic.rs instead of hello
using the parameter `hello` results in the following error.

```text
error: no example target named `hello`
```